name: Ruby on Rails CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: monobank_progress_jar_backend_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.1

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
     
    - name: Security audit dependencies
      run: bundle exec bundler-audit
      
    - name: Security audit application code
      run: bundle exec brakeman -q -w2
      
    - name: Lint Ruby files
      run: bundle exec rubocop --parallel